spring:
  application:
    name: Event Management App


  #JPA
  jpa:
    show-sql: true

  #Spring Datasource Connection Pooling configuration
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/event_management_db?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      validation-query: SELECT 1
      max-active: 5
      max-idle: 3
      max-wait: 8000

  #Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:3306?useSSL=false
    schemas: event_management_db
    user: root
    password: